Form/Type/EditorType.php
<?php

namespace ServerGrove\KbBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class EditorType
 *
 * @author Ismael Ambrosi<ismael@servergrove.com>
 */
class EditorType extends AbstractType
{

    private $type;

    public function __construct($type)
    {
        $this->type = $type;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['type'] = $options['type'];
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array('type' => $this->type));
        $resolver->setAllowedValues(array('type' => array('markdown', 'wysiwyg')));
    }

    public function getParent()
    {
        return 'textarea';
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'sg_editor';
    }
}

Resources/views/layout.html.twig
<!DOCTYPE html>
<html ng-app="{% block ng_app %}ServerGroveKb{% endblock ng_app %}">
<head>
    <title>{% block title %}Knowledge Base{% endblock %}</title>
    {% block metas %}{% endblock %}
    {% block javascripts %}
    {% spaceless %}
    {% javascripts
        "@ServerGroveKbBundle/Resources/public/js/0.jquery-1.7.2.min.js"
        "@ServerGroveKbBundle/Resources/public/js/1.angular-1.0.1.min.js"
        "@ServerGroveKbBundle/Resources/public/js/2.bootstrap-2.0.4.min.js"
        "@ServerGroveKbBundle/Resources/public/js/3.prettify.js"
        "@ServerGroveKbBundle/Resources/public/js/jquery.ez-pinned-footer.js"
        "@ServerGroveKbBundle/Resources/public/js/frontend/frontend.js"
        "@ServerGroveKbBundle/Resources/public/js/google-code-prettify/*.js"
        filter="?yui_js" output="/js/compiled/frontend.js" %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    {% endspaceless %}
    {% endblock %}
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Project name</a>

        </div>
    </div>
</div>

<div class="subnav">
    <div class="nav-collapse">
        <div class="container">

            <div class="row">

                {% block body %}
                {% block preheader %}{% endblock preheader %}
                <div class="title-page">
                    {% block postheader %}{% endblock postheader %}
                </div>
                {% include "ServerGroveKbBundle:Default:breadcrumb.html.twig" %}
                <div class="span2">
                    {% render "ServerGroveKbBundle:Categories:selector" with { 'topCategory': category is defined ?
                            category.getTopCategory() :
                            article is defined ?
                            article.getDefaultCategory().getTopCategory() : null
                            } %}
                </div>
                <div class="span10">
                    {% render "ServerGroveKbBundle:Default:searchForm" %}
                    {% block content %}{% endblock content %}
                </div>


            </div>


            <hr>

            <footer>
                <p>&copy; Company 2012</p>
            </footer>


        </div>
    </div>
</div>

{% block prefooter %}{% endblock prefooter %}
{% block postfooter %}{% endblock postfooter %}
{% endblock body %}
</body>
</html>

Resources/views/layout.rss.twig
{% spaceless %}
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
    <channel>
        <title>{% block title %}{% endblock %}</title>
        <description>{% block description %}{% endblock %}</description>
        <lastBuildDate>{{ "now"|date('D, d M Y H:i:s') }}}</lastBuildDate>
        {% block items %}
        {% endblock %}
    </channel>
</rss>
{% endspaceless %}

Resources/views/macros.html.twig
{% macro displayCategoryBreadcrumb(category, active, admin) %}

    {% if category.parent.path is defined %}
        {{ _self.displayCategoryBreadcrumb(category.getParent(), false, admin) }}
    {% endif %}

    {% set route = admin|default(false) ? "sgkb_admin_categories_show" : "sgkb_categories_view" %}
    <li{% if active|default(false) %} class="active" {% endif %}>
        <a class="alllower" href="{{ path(route, {'path': category.getPath(), '_format': 'html'}) }}">{{ category.getName() }}</a>

        {% if not active|default(false) %}
            <span class="divider">/</span>
        {% endif %}
    </li>

{% endmacro %}

{% macro displayArticleBreadcrumb(article, category, admin) %}

    {{ _self.displayCategoryBreadcrumb(category, false, admin) }}

    {% set route = admin|default(false) ? "sgkb_admin_articles_show" : "sgkb_articles_view" %}
    <li class="active">
        <a class="alllower" href="{{ path(route, {'path': category.getPath(), 'slug': article.getSlug(), '_format': 'html'}) }}">{{ article.getTitle() }}</a>
    </li>

{% endmacro %}

{% macro displayBreadcrumb(article, category, admin) %}
    {% spaceless %}
        {% set admin = admin|default(false) %}
        {% set article = article|default(false) %}
        {% set category = category|default(false) %}
        <ul class="breadcrumb">
            <li>
                <a class="alllower" href="{{ path(admin ? 'sgkb_admin_categories_index' : 'sgkb_index_locale', {'_locale': app.request.locale}) }}">{% trans %}Home{% endtrans %}</a>
                {% if category or article %}<span class="divider">/</span>{% endif %}
            </li>

            {% if category %}
                {% if article %}
                    {{ _self.displayArticleBreadcrumb(article, category, admin) }}
                {% else %}
                    {{ _self.displayCategoryBreadcrumb(category, true, admin) }}
                {% endif %}
            {% elseif article %}
                {{ _self.displayArticleBreadcrumb(article, article.getDefaultCategory(), admin) }}
            {% endif %}
        </ul>
    {% endspaceless %}
{% endmacro %}